CREATE TABLE IF NOT EXISTS song_infos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    music_id INTEGER UNIQUE NOT NULL,
    song_name TEXT NOT NULL,
    song_artists TEXT NOT NULL,
    song_album TEXT NOT NULL,
    file_ext TEXT NOT NULL DEFAULT 'mp3',
    music_size INTEGER NOT NULL DEFAULT 0,
    pic_size INTEGER NOT NULL DEFAULT 0,
    emb_pic_size INTEGER NOT NULL DEFAULT 0,
    bit_rate INTEGER NOT NULL DEFAULT 0,
    duration INTEGER NOT NULL DEFAULT 0,
    file_id TEXT,
    thumb_file_id TEXT,
    from_user_id INTEGER NOT NULL,
    from_user_name TEXT NOT NULL,
    from_chat_id INTEGER NOT NULL,
    from_chat_name TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
